import 'package:sqflite/sqflite.dart';
import '../../core/database/database.service.dart';
import 'models/customer.model.dart';
import '../../core/database/scripts/customer_table.dart';

class CustomerService {
  final DatabaseService _databaseService = DatabaseService();

  Future<List<Customer>> getCustomers({String? query}) async {
    final db = await _databaseService.database;
    final List<Map<String, dynamic>> maps;

    if (query != null && query.isNotEmpty) {
      maps = await db.query(
        CustomerTable.tableName,
        where: 'name LIKE ? OR phone LIKE ?',
        whereArgs: ['%$query%', '%$query%'],
        orderBy: 'name ASC',
      );
    } else {
      maps = await db.query(CustomerTable.tableName, orderBy: 'name ASC');
    }

    return List.generate(maps.length, (i) => Customer.fromMap(maps[i]));
  }

  Future<int> createCustomer(Customer customer) async {
    final db = await _databaseService.database;
    return await db.insert(
      CustomerTable.tableName,
      customer.toMap()..remove('id'), // Ensure ID is generated by DB
      conflictAlgorithm: ConflictAlgorithm.replace,
    );
  }
}
